const WEAVR = process.env.VUE_APP_WEAVR_ADDRESS;
const FRBC = process.env.VUE_APP_TOKEN_ADDRESS;
const THREAD_DEPLOYER = process.env.VUE_APP_THREAD_DEPLOYER_ADDRESS;
const BOND = process.env.VUE_APP_BOND_ADDRESS;
const BEACON = process.env.VUE_APP_BEACON_ADDRESS;
const FRABRIC_CODE = process.env.VUE_APP_FRABRIC_CODE_ADDRESS;
exports.CONTRACTS = { WEAVR, FRBC, THREAD_DEPLOYER, BOND, BEACON, FRABRIC_CODE };
exports.DAO = "weavr"